Repository DSpace/RestContract, pull requests merged in 2020-08, with the labels that each got.

#131 DS-4514 start a new submission via file
  workspaceitems.md
Labels: 1 APPROVAL, e/24

#145 Metadata field: retrieve by exact name
  metadatafields.md
Labels: 1 APPROVAL, high priority

#147 Search processes
  processes-endpoint.md
Labels: 1 APPROVAL
