Repository DSpace/RestContract, pull requests merged in 2022-06, with the labels that each got.

#195 RelationshipType embedding from relationships
  relationships.md
Labels: 1 APPROVAL

#182 [CST-5288] Added spring boot actuators on endpoints contract
  actuator.md
  endpoints.md
Labels: high priority

#188 Sherpa-Romeo Integration Rest Contract
  submissionsection-types.md
  workspaceitem-data-sherpa-policy.md
Labels: medium priority

#190 Update ORCID synchronization preferences
  profiles.md
Labels: high priority

#196 Feature relationship versioning: remove warning
  version.md
Labels: high priority, 1 APPROVAL

#189 Orcid queue and orcid history contract
  endpoints.md
  orcidhistories.md
  orcidqueues.md
Labels: high priority
