Repository DSpace/RestContract, pull requests merged in 2023-06, with the labels that each got.

#203 REST Contract for the delete multiple bitstreams endpoint
  README.md
  bitstreams.md
Labels: high priority

#228 Added return codes to the Metadata Schemas & Fields Endpoints
  metadatafields.md
  metadataschemas.md
Labels: bug, 1 APPROVAL

#227 [CST-5728] LYRASIS [Donated]: DSpace7: Implement signposting pattern …
  endpoints.md
  signposting.md
Labels: claimed: 4Science

#222 Primary bitstream
  bundles.md
Labels: bug, high priority

#223 REST Contract for the Bulk Access Control Management feature
  bulkaccessconditionoptions.md
  endpoints.md
  scripts/bulk-access-control.md
Labels: high priority, claimed: 4Science

#233 Fix outdated references and example URLs in entitytypes.md
  entitytypes.md
Labels: 1 APPROVAL

#235 [DURACOM-156] Singposting: feedback after initial deployment
  signposting.md
Labels: 1 APPROVAL
