Repository DSpace/RestContract, pull requests merged in 2024-02, with the labels that each got.

#253 New 'creationTime' sort option for '/search/byProperty' in processes contract
  processes-endpoint.md
Labels: 1 APPROVAL, tools: processes

#192 Openaire suggestions (publication claim) rest contracts
  endpoints.md
  suggestions.md
  suggestionsources.md
  suggestiontargets.md
Labels: high priority, integration: OpenAIRE, integration: QA Notifications

#254 Renamed singular endpoints to their plural version
  authorizations.md
  endpoints.md
  items.md
  search-rels.md
  statistics-reports.md
  submissionuploads.md
  subscriptions.md
  versionhistories.md
  versions.md
Labels: 1 APPROVAL

#250 Add support for a DSpace internal quality assurance source
  correctiontypes.md
  qualityassuranceevents.md
Labels: high priority, new feature, integration: QA Notifications

#249 Coar Notify Integration
  itemfilters.md
  ldnservices.md
  qualityassuranceevents.md
  qualityassurancesources.md
  qualityassurancetopics.md
  submissioncoarnotifyconfigs.md
  workspaceitem-data-coarnotify.md
Labels: high priority, new feature, integration: COAR Notify / LDN
